## Extracción del Dataset principal.

Este dataset muestra la producción de equipos electrónicos fabricados en TDF

In [4]:
import pandas as pd

file_name = "/content/drive/MyDrive/Colab Notebooks/Proyecto AprendAutom/14_3_03_Produccion_Industrial-1-1.xlsx"

df_produccion = pd.read_excel(file_name, sheet_name="ELECTRONICA", header=3)
df_produccion = df_produccion.rename(columns={
        'Unnamed: 0': 'Año',
        'Unnamed: 1': 'Mes',
        'Unnamed: 2': 'Total'})
df_produccion = df_produccion.iloc[2:].copy()
df_produccion = df_produccion.iloc[:-5].copy()
df_produccion

,Año,Mes,Total,Acondicionador de Aire,Afeitadora Eléctrica,Aspiradora,Autorradio,Cámara Fotográfica Digital,Computadora Portátil,Decodificador de Video,...,Lavarropas,Módem,Módulo Electrónico para Automotor,Monitor,Reproductor de Video,Sistema de Audio,Tablet PC,Televisor,Unidades Evaporadoras- Condensadoras,Videocámara
2,2013,Ene,1260521,77671.0,17400,0,10922.0,31894,125926,93071,...,273,0,23797.0,43086,26593,10999,4204,136796.0,966,4519
3,NaN,Feb,1559546,90403.0,34000,0,20220.0,23598,100638,157971,...,1561,0,26602.0,65445,43981,21666,10796,207715.0,4944,6090
4,NaN,Mar,1935759,115115.0,45120,0,31615.0,31864,71560,209723,...,3353,0,36371.0,28534,47839,27683,0,288394.0,3041,6992
5,NaN,Apr,2072806,78426.0,38320,0,24317.0,20519,115290,234551,...,776,0,39229.0,24764,58850,21227,0,268295.0,1257,5966
6,NaN,May,2538083,108772.0,49380,1438,36265.0,26406,137272,298732,...,2296,0,48379.0,40177,67549,25283,0,320475.0,722,4174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,NaN,Nov*,1260593,198554.0,-,-,23614.0,-,-,-,...,-,-,37837.0,14969,-,2864,-,247424.0,-,-
145,NaN,Dic*,1099022,216260.0,-,-,16239.0,-,-,-,...,-,-,17606.0,8072,-,88,-,189205.0,120,-
146,2025,Ene*,773676,102142.0,-,-,25573.0,-,-,-,...,-,-,28338.0,10470,-,-,-,196924.0,12,-
147,NaN,Feb*,935562,67686.0,-,-,30438.0,-,-,-,...,-,-,40067.0,8025,-,411,-,230022.0,-,-
148,NaN,Mar*,887363,51056.0,-,-,30706.0,NaN,NaN,NaN,...,-,-,18566.0,11587,-,1365,-,228300.0,-,-

In [5]:
df_produccion.columns = df_produccion.columns.str.strip()

# Columnas a conservar
columnas_deseadas = [
    'Año',
    'Mes',
    'Total',
    'Acondicionador de Aire',
    'Equipo de Radiocomunicaciones Móviles Celulares',
    'Horno/Cocina a Microondas',
    'Televisor',
    'Módulo Electrónico para Automotor']
df_produc_features = df_produccion[columnas_deseadas]
# Renombrar las columnas
df_produc_features = df_produc_features.rename(columns={
        'Acondicionador de Aire': 'Aireacondicionado',
        'Equipo de Radiocomunicaciones Móviles Celulares': 'Celulares',
        'Horno/Cocina a Microondas': 'Microondas',
        'Módulo Electrónico para Automotor': 'Mod Electr Autom'})
print("DataFrame 'df_produc_features' con solo las columnas deseadas:")
print(df_produc_features)

DataFrame 'df_produc_features' con solo las columnas deseadas:
      Año   Mes    Total  Aireacondicionado  Celulares  Microondas  Televisor  \
2    2013   Ene  1260521            77671.0   609990.0     38094.0   136796.0
3     NaN   Feb  1559546            90403.0   703500.0     32936.0   207715.0
4     NaN   Mar  1935759           115115.0   918733.0     62302.0   288394.0
5     NaN   Apr  2072806            78426.0  1083534.0     46865.0   268295.0
6     NaN   May  2538083           108772.0  1293334.0     63549.0   320475.0
..    ...   ...      ...                ...        ...         ...        ...
144   NaN  Nov*  1260593           198554.0   716903.0     18428.0   247424.0
145   NaN  Dic*  1099022           216260.0   633913.0     17519.0   189205.0
146  2025  Ene*   773676           102142.0   393358.0     16859.0   196924.0
147   NaN  Feb*   935562            67686.0   557773.0      1140.0   230022.0
148   NaN  Mar*   887363            51056.0   545686.0        97.0   228300.0

     Mod Electr Autom
2             23797.0
3             26602.0
4             36371.0
5             39229.0
6             48379.0
..                ...
144           37837.0
145           17606.0
146           28338.0
147           40067.0
148           18566.0

[147 rows x 8 columns]

In [6]:
# rellenar los valores del año correspondiente
df_produc_features['Año'] = df_produc_features['Año'].ffill()
df_produc_features['Año'] = df_produc_features['Año'].astype(int)

# Cambiar el tipo de datos de las columnas restantes
columnas_a_entero = [
    'Total',
    'Aireacondicionado',
    'Celulares',
    'Microondas',
    'Televisor',
    'Mod Electr Autom' ]

for col in columnas_a_entero:
    if col in df_produc_features.columns:
        df_produc_features[col] = df_produc_features[col].astype(int)
    else:
        print(f"Advertencia: La columna '{col}' no se encontró en el DataFrame.")

print("\nDataFrame 'df_produc_features' después del cambio de tipos:")
print(df_produc_features)

DataFrame 'df_produc_features' después del cambio de tipos:
      Año   Mes    Total  Aireacondicionado  Celulares  Microondas  Televisor  \
2    2013   Ene  1260521              77671     609990       38094     136796
3    2013   Feb  1559546              90403     703500       32936     207715
4    2013   Mar  1935759             115115     918733       62302     288394
5    2013   Apr  2072806              78426    1083534       46865     268295
6    2013   May  2538083             108772    1293334       63549     320475
..    ...   ...      ...                ...        ...         ...        ...
144  2024  Nov*  1260593             198554     716903       18428     247424
145  2024  Dic*  1099022             216260     633913       17519     189205
146  2025  Ene*   773676             102142     393358       16859     196924
147  2025  Feb*   935562              67686     557773        1140     230022
148  2025  Mar*   887363              51056     545686          97     228300

     Mod Electr Autom
2               23797
3               26602
4               36371
5               39229
6               48379
..                ...
144             37837
145             17606
146             28338
147             40067
148             18566

[147 rows x 8 columns]

<ipython-input-6-3170301906>:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_produc_features['Año'] = df_produc_features['Año'].ffill()

In [7]:
print("\nInformación del DataFrame 'df_produc_features':")
print(df_produc_features.info())

Información del DataFrame 'df_produc_features':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 2 to 148
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Año                147 non-null    int64
 1   Mes                147 non-null    object
 2   Total              147 non-null    int64
 3   Aireacondicionado  147 non-null    int64
 4   Celulares          147 non-null    int64
 5   Microondas         147 non-null    int64
 6   Televisor          147 non-null    int64
 7   Mod Electr Autom   147 non-null    int64
dtypes: int64(7), object(1)
memory usage: 9.3+ KB
None

In [8]:
# Guardar dataset generado
if not df_produc_features.empty:
  df_produc_features.to_excel('Produccion_Industrial-Preprocesado.xlsx', index=False)
  print("La tabla se ha guardado como 'Produccion_Industrial-Preprocesado.xlsx'")
else:
  print("No hay tabla para guardar.")

La tabla se ha guardado como 'Produccion_Industrial-Preprocesado.xlsx'